server:
  port: 8001

# Spring 配置
spring:
  # 数据源配置
  datasource:
    # mysql 服务器配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://101.132.43.13:3306/hello?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/hello?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认 600000s（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 1000
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认 1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认 30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # Redis 服务器配置
  redis:
    host: 101.132.43.13
    port: 6379
    password: root
    database: 0
    # 连接超时时间
    timeout: 30000
    lettuce:
      pool:
        # 最大连接数，默认 8
        max-active: 30
        # 最大连续阻塞等待时间，单位毫秒，默认 -1ms
        max-wait: 20000
        # 最大空闲连接，默认 8
        max-idle: 30
        # 最小空闲连接，默认 0
        min-idle: 10

# MyBatis-plus 配置
mybatis-plus:
  # 配置 mapper 映射文件
  mapper-locations: classpath*:mapper/*Mapper.xml
  # 配置 MyBatis 数据返回类型别名（默认别名是类名）
  type-aliases-package: com.ukyang.server.model
  configuration:
    # 自动驼峰命名（关闭）
    map-underscore-to-camel-case: false

logging:
  level:
    # MyBatis SQL 打印（方法接口所在的包，不是 mapper 所在的包）
    com.ukyang.server.mapper: error
  config:
    classpath:config/logback.xml